"""Built-in SparkVM guest init template."""

from .debian import DEBIAN_MINBASE_IMAGE_ID, INIT_TEMPLATE, SPARKVM_INIT_TEMPLATE

__all__ = ["SPARKVM_INIT_TEMPLATE", "INIT_TEMPLATE", "DEBIAN_MINBASE_IMAGE_ID"]
